[package]
name = "mullvm-parser"
version = "0.1.0"
edition = "2021"
authors = ["William Tange <will@tan.ge>"]
license = "MIT OR Apache-2.0"

[dependencies]
clang-sys = "1.7.0"
clap = { version = "4.4.18", features = ["derive"] }
clap-verbosity-flag = "2.1.2"
pest = "2.7.6"
pest_derive = "2.7.6"
